//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Customers = new HashSet<Customer>();
            this.Locations = new HashSet<Location>();
            this.Projects = new HashSet<Project>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public Nullable<int> SupportAgreementID { get; set; }
        public Nullable<int> DescriptionID { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Description Description { get; set; }
        public virtual SupportAgreement SupportAgreement { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
