//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInformation
    {
        public int Id { get; set; }
        public Nullable<int> EmailAddressID { get; set; }
        public Nullable<int> MailingAddressID { get; set; }
        public Nullable<int> PhoneNumberID { get; set; }
    
        public virtual EmailAddress EmailAddress { get; set; }
        public virtual MailingAddress MailingAddress { get; set; }
        public virtual PhoneNumber PhoneNumber { get; set; }
    }
}
