//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.CLOUs = new HashSet<CLOU>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<CLOU> CLOUs { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
