//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public PhoneNumber()
        {
            this.ContactInformations = new HashSet<ContactInformation>();
        }
    
        public int Id { get; set; }
        public string PhoneNumber1 { get; set; }
        public Nullable<int> PhoneNumberTypeID { get; set; }
    
        public virtual ICollection<ContactInformation> ContactInformations { get; set; }
        public virtual PhoneNumberType PhoneNumberType { get; set; }
    }
}
