//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> DescriptionID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Description Description { get; set; }
        public virtual Status Status { get; set; }
    }
}
