//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Projects = new HashSet<Project>();
            this.SupportEvents = new HashSet<SupportEvent>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<SupportEvent> SupportEvents { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
