//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportEvent
    {
        public int Id { get; set; }
        public System.DateTime DateTimeOpened { get; set; }
        public Nullable<System.DateTime> DateTimeClosed { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> DescriptionID { get; set; }
    
        public virtual Description Description { get; set; }
        public virtual Status Status { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
