//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteWaveApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.SupportEvents = new HashSet<SupportEvent>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> EmployeeOpenedID { get; set; }
        public Nullable<int> DescriptionID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Description Description { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<SupportEvent> SupportEvents { get; set; }
    }
}
